name: ad156b2b
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU user emulation
        run: |
          sudo apt-get -y update
          sudo apt-get install -y qemu-user-binfmt
          sudo update-binfmts --display

      - name: Test
        run: |
          sudo docker run --rm arm64v8/ubuntu uname -a
