name: ad156b2b
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU user emulation
        run: |
          sudo apt-get -y update
          sudo apt-get -y install binfmt-support qemu-user-binfmt qemu-user-static
      
      - name: Test
        run: |
          sudo docker run --rm arm64v8/ubuntu uname -a
