name: ad156b2b
on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Shell script'
        required: true
        default: "echo 'hello world'"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: apt list | grep binfmt
